In [1]:
import array
import numpy as np

# Crear un arreglo con 9 elementos
elementos = array.array('f', [1, 2, 3, 4, 5, 6, 7, 8, 9])

# Extraer los elementos para formar la matriz sin ciclos ni funciones adicionales
fila1 = elementos[:3]
fila2 = elementos[3:6]
fila3 = elementos[6:]

# Crear la matriz a partir de las filas
matriz = np.array([fila1, fila2, fila3])

matriz



array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [3]:
def elem(A, i, j):
    # Calcula el índice correspondiente en el arreglo 1D
    index = i * 3 + j
    return A[index]


# Obtener el elemento en la posición (1, 2) (fila 1, columna 2)
fila = 2
columna = 2
elemento = elem(elementos, fila, columna)

print(f"El elemento en la posición ({fila}, {columna}) es: {elemento}")


El elemento en la posición (2, 2) es: 9


In [4]:
# Obtener un elemento de la matriz
# Renglón 0 y columna 0
# Recuerde que comienza desde cero
matriz[1,0]

4

In [5]:
# Intercambiar el renglón 0 con el renglón 1,
# R0 <-> R1

matriz[[0,1],:] = matriz[[1,0],:]
matriz

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]], dtype=int32)

In [3]:
# Multiplicar el renglón 0  por un 1/2,
# (1/2)R0 -> R0

matriz[0,:] *= 1/2   #  B[0,:] = B[0,:]*1/2
matriz

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [7]:
# Suma (-4) veces el renglón 0 al renglón 2,
# -4R0 + R2 -> R2

matriz[2,:] += -4*matriz[0,:]  #  B[2,:] = B[2,:] + (-4)*B[0,:]
matriz

array([[  8,  10,  12],
       [  1,   2,   3],
       [-25, -32, -39]], dtype=int32)